import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { createApi } from "./server/api.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");

// The committed, durable data: per-page OCR JSON + classify_report.json under
// sources/gpp/volumes/ocr/<stem>/. Works from a fresh clone, no local render
// step needed. Override with OCR_DIR=/path npm run dev.
const ocrRoot = path.resolve(
  repoRoot,
  process.env.OCR_DIR || "sources/gpp/volumes/ocr",
);

// Local scratch render output (raw/ + overlays/ PNGs) -- NOT committed,
// regenerated by running scripts/run_volume_ocr.py locally. Same location
// that script already writes to. Override with RENDERS_DIR=/path npm run dev.
const rendersRoot = path.resolve(
  repoRoot,
  process.env.RENDERS_DIR || "vlm-ocr-runs",
);

const volumesJson = path.resolve(repoRoot, "sources/gpp/volumes.json");

// Serve the volume data through the same server that serves the app, so
// `npm run dev` (or `npm run preview`) is the only process needed.
const volumesApi = () => ({
  name: "qa-ui-volumes-api",
  configureServer(server) {
    server.middlewares.use(createApi({ ocrRoot, rendersRoot, volumesJson }));
  },
  configurePreviewServer(server) {
    server.middlewares.use(createApi({ ocrRoot, rendersRoot, volumesJson }));
  },
});

export default defineConfig({
  base: process.env.VITE_BASE || "/",
  plugins: [react(), volumesApi()],
  server: { port: 5274, open: true },
});
