#!/usr/bin/env python3
"""Regenerate the tiny offline PDF fixtures for the parse pipeline.

Six fixtures, all minimal and deterministic (committed to the repo):

  * ``born_digital_sample.pdf`` — a real text-layer PDF built with PyMuPDF.
    It embeds a hyphenated line-wrap ("adminis-" / "tration") so the extractor's
    dehyphenation can be asserted, plus two paragraphs so paragraph-break
    preservation can be checked.

  * ``scanned_sample.pdf`` — the SAME content rendered to a raster image and
    wrapped image-only (no text layer), so ``textlayer`` classifies it "scanned"
    and ``ocr`` must recover the words locally.

  * ``ocr_layer_sample.pdf`` — the raster page with the text stamped back over it
    in PDF render mode 3 (invisible). This is the signature of a scan somebody
    already ran through OCR: it has an extractable text layer, and that layer is
    a machine's guess at a photograph rather than the document. 665 of the 1,205
    records the density probe alone called born-digital have this shape.

  * ``mixed_pages_sample.pdf`` — page 1 born-digital, page 2 image-only. The mean
    chars/page still clears the gate, so the whole document passes and page 2 is
    published as nothing. This is the 2025-EO-057 shape, which publishes a body
    beginning mid-order at "$ 2." with its entire first page missing.

  * ``broken_font_sample.pdf`` — a text layer whose glyphs map to the wrong
    characters, so the extracted text is well-formed nonsense. This is the
    2025-EEO-853 / 854 shape: 2,354 characters reading "Jo,(uIi{ / slu€pv cug".
    _word_ratio scores it 0.848, comfortably inside the "clean" band; only the
    lexicon sees it.

  * ``paragraphs_sample.pdf`` — two blocks with tight leading inside and wide
    leading between, so the paragraph-geometry rule has a deterministic target.

Run: ``python tests/fixtures/generate_fixtures.py`` (needs PyMuPDF only, offline).
The generated bytes are committed; this script exists so the fixtures are
reproducible, not guessed (engineering-standards §0).
"""

from __future__ import annotations

from pathlib import Path

import fitz  # PyMuPDF

HERE = Path(__file__).parent

# The lines of the born-digital fixture. The trailing "adminis-" on one line and
# leading "tration" on the next is the dehyphenation probe. "OVERSIGHT" is a
# distinctive token OCR can be checked against.
LINES = [
    "EXECUTIVE ORDER NO. 42",
    "",
    "WHEREAS, the City establishes an office of data adminis-",
    "tration to advance transparency and public OVERSIGHT; and",
    "",
    "NOW, THEREFORE, by the power vested in the Mayor, it is",
    "hereby ordered that the office shall commence operations.",
]

# Page 2 of the mixed fixture: image-only, so it extracts to nothing while the
# document's mean chars/page still clears the gate.
PAGE_TWO_LINES = [
    "SECTION 2. This Executive Order shall take effect immediately",
    "and shall remain in effect until rescinded by the Mayor.",
]

# The broken-font fixture's visible nonsense. Deliberately vowel-bearing with no
# run of five consonants, so _english_like accepts almost every token and the
# word ratio lands in the "clean" band -- exactly what makes 2025-EEO-853 pass.
BROKEN_FONT_LINES = [
    "Jo culi slucpv cug wY entare mo bilate",
    "Sero mi tuca de lorane pu tise vo canile",
    "Bane tu selore vi macuna te polire so vane",
]

# Tight leading inside a block, wide leading between blocks. 12pt lines at 14pt
# leading inside and 30pt between: a ratio of 2.1, well clear of the 1.35 rule.
PARAGRAPH_BLOCKS = [
    ["WHEREAS, the first clause runs across two printed lines and",
     "must therefore stay a single paragraph in the emitted body; and"],
    ["WHEREAS, the second clause is a separate paragraph and must be",
     "separated from the first by a blank line in the emitted body; and"],
    ["NOW, THEREFORE, it is hereby ordered as set forth below."],
]


def build_born_digital(path: Path) -> None:
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)  # US Letter
    y = 72.0
    for line in LINES:
        if line:
            # 11pt Helvetica; insert_text places a single unwrapped line, so the
            # hyphenated wrap is preserved exactly as authored.
            page.insert_text((72, y), line, fontsize=11, fontname="helv")
        y += 22.0
    doc.save(path)
    doc.close()


def build_scanned(src_path: Path, path: Path) -> None:
    """Rasterize the born-digital page and wrap it image-only (no text layer)."""
    src = fitz.open(src_path)
    page = src[0]
    width, height = page.rect.width, page.rect.height
    # Grayscale @150 DPI: legible to Tesseract, but 1/3 the bytes of RGB. Wrapped
    # image-only (no text layer) so it classifies "scanned".
    pix = page.get_pixmap(dpi=150, colorspace=fitz.csGRAY)
    src.close()

    out = fitz.open()
    img_page = out.new_page(width=width, height=height)
    img_page.insert_image(img_page.rect, pixmap=pix)
    # Flate-compress the embedded image and drop cruft so the committed fixture
    # stays small (well under a few hundred KB).
    out.save(path, deflate=True, deflate_images=True, garbage=4)
    out.close()


def _raster_page(src_path: Path, out: fitz.Document, dpi: int = 150):
    """Append the source PDF's first page to `out` as a bare image, and return it."""
    src = fitz.open(src_path)
    page = src[0]
    width, height = page.rect.width, page.rect.height
    pix = page.get_pixmap(dpi=dpi, colorspace=fitz.csGRAY)
    src.close()
    img_page = out.new_page(width=width, height=height)
    img_page.insert_image(img_page.rect, pixmap=pix)
    return img_page


def build_ocr_layer(src_path: Path, path: Path) -> None:
    """The raster page with its text stamped back INVISIBLY over the image.

    ``render_mode=3`` is "neither fill nor stroke" (PDF 32000-1:2008 section
    9.3.6) — the mode every OCR-overlay writer uses so the recognized text is
    selectable and searchable without covering the scan it came from. The result
    extracts as ordinary text and looks born-digital to a character-density
    probe, which is exactly the failure this fixture exists to catch.
    """
    out = fitz.open()
    img_page = _raster_page(src_path, out)
    y = 72.0
    for line in LINES:
        if line:
            img_page.insert_text((72, y), line, fontsize=11, fontname="helv",
                                 render_mode=3)
        y += 22.0
    out.save(path, deflate=True, deflate_images=True, garbage=4)
    out.close()


def build_mixed_pages(src_path: Path, path: Path) -> None:
    """Page 1 born-digital, page 2 image-only — inside ONE document.

    The mean is what the density gate reads, and the mean still clears it. So the
    document passes as born-digital and page 2 contributes nothing to the emitted
    body, with no code path saying so.
    """
    out = fitz.open()
    page1 = out.new_page(width=612, height=792)
    y = 72.0
    for line in LINES:
        if line:
            page1.insert_text((72, y), line, fontsize=11, fontname="helv")
        y += 22.0

    # Page 2: render the text to a raster and embed it, so it carries ink but no
    # extractable character.
    scratch = fitz.open()
    tmp = scratch.new_page(width=612, height=792)
    y = 72.0
    for line in PAGE_TWO_LINES:
        tmp.insert_text((72, y), line, fontsize=11, fontname="helv")
        y += 22.0
    pix = tmp.get_pixmap(dpi=150, colorspace=fitz.csGRAY)
    scratch.close()
    page2 = out.new_page(width=612, height=792)
    page2.insert_image(page2.rect, pixmap=pix)

    out.save(path, deflate=True, deflate_images=True, garbage=4)
    out.close()


def build_broken_font(path: Path) -> None:
    """A text layer that extracts to well-formed nonsense.

    The real documents (2025-EEO-853/854) have a broken glyph-to-Unicode map, so
    every character comes out as the wrong character. The shape that matters
    downstream is what the metrics see: tokens that LOOK like words —
    pronounceable, vowel-bearing, no five-consonant run — and are not words.
    _word_ratio rates the real pair 0.848 and 0.851, above the 0.70 review floor.
    Writing the nonsense directly reproduces that shape without depending on a
    hand-corrupted font table.
    """
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    y = 72.0
    # Repeated so the body is long enough for a ratio to be meaningful rather
    # than dominated by one or two tokens.
    for _ in range(8):
        for line in BROKEN_FONT_LINES:
            page.insert_text((72, y), line, fontsize=11, fontname="helv")
            y += 14.0
    doc.save(path)
    doc.close()


def build_paragraphs(path: Path) -> None:
    """Tight leading inside a block, wide leading between blocks.

    PyMuPDF returns one line per printed line and nothing about paragraphs, so
    the only signal for a paragraph break is the vertical gap. 14pt inside
    against 30pt between is a ratio of 2.1 — the real corpus measures 13.8
    against 27.6 (2022-EO-023), so this fixture is faithful, not generous.
    """
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    y = 72.0
    for block in PARAGRAPH_BLOCKS:
        for line in block:
            page.insert_text((72, y), line, fontsize=11, fontname="helv")
            y += 14.0
        y += 16.0        # 14 + 16 = 30pt between blocks
    doc.save(path)
    doc.close()


def main() -> None:
    born = HERE / "born_digital_sample.pdf"
    scanned = HERE / "scanned_sample.pdf"
    ocr_layer = HERE / "ocr_layer_sample.pdf"
    mixed = HERE / "mixed_pages_sample.pdf"
    broken = HERE / "broken_font_sample.pdf"
    paragraphs = HERE / "paragraphs_sample.pdf"
    build_born_digital(born)
    build_scanned(born, scanned)
    build_ocr_layer(born, ocr_layer)
    build_mixed_pages(born, mixed)
    build_broken_font(broken)
    build_paragraphs(paragraphs)
    for f in (born, scanned, ocr_layer, mixed, broken, paragraphs):
        print(f"wrote {f} ({f.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
