#!/usr/bin/env python3
"""Regenerate the tiny offline PDF fixtures for the parse pipeline.

Two fixtures, both minimal and deterministic (committed to the repo):

  * ``born_digital_sample.pdf`` — a real text-layer PDF built with PyMuPDF.
    It embeds a hyphenated line-wrap ("adminis-" / "tration") so the extractor's
    dehyphenation can be asserted, plus two paragraphs so paragraph-break
    preservation can be checked.

  * ``scanned_sample.pdf`` — the SAME content rendered to a raster image and
    wrapped image-only (no text layer), so ``textlayer`` classifies it "scanned"
    and ``ocr`` must recover the words locally.

Run: ``python tests/fixtures/generate_fixtures.py`` (needs PyMuPDF only, offline).
The generated bytes are committed; this script exists so the fixtures are
reproducible, not guessed (engineering-standards §0).
"""

from __future__ import annotations

from pathlib import Path

import fitz  # PyMuPDF

HERE = Path(__file__).parent

# The lines of the born-digital fixture. The trailing "adminis-" on one line and
# leading "tration" on the next is the dehyphenation probe. "OVERSIGHT" is a
# distinctive token OCR can be checked against.
LINES = [
    "EXECUTIVE ORDER NO. 42",
    "",
    "WHEREAS, the City establishes an office of data adminis-",
    "tration to advance transparency and public OVERSIGHT; and",
    "",
    "NOW, THEREFORE, by the power vested in the Mayor, it is",
    "hereby ordered that the office shall commence operations.",
]


def build_born_digital(path: Path) -> None:
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)  # US Letter
    y = 72.0
    for line in LINES:
        if line:
            # 11pt Helvetica; insert_text places a single unwrapped line, so the
            # hyphenated wrap is preserved exactly as authored.
            page.insert_text((72, y), line, fontsize=11, fontname="helv")
        y += 22.0
    doc.save(path)
    doc.close()


def build_scanned(src_path: Path, path: Path) -> None:
    """Rasterize the born-digital page and wrap it image-only (no text layer)."""
    src = fitz.open(src_path)
    page = src[0]
    width, height = page.rect.width, page.rect.height
    # Grayscale @150 DPI: legible to Tesseract, but 1/3 the bytes of RGB. Wrapped
    # image-only (no text layer) so it classifies "scanned".
    pix = page.get_pixmap(dpi=150, colorspace=fitz.csGRAY)
    src.close()

    out = fitz.open()
    img_page = out.new_page(width=width, height=height)
    img_page.insert_image(img_page.rect, pixmap=pix)
    # Flate-compress the embedded image and drop cruft so the committed fixture
    # stays small (well under a few hundred KB).
    out.save(path, deflate=True, deflate_images=True, garbage=4)
    out.close()


def main() -> None:
    born = HERE / "born_digital_sample.pdf"
    scanned = HERE / "scanned_sample.pdf"
    build_born_digital(born)
    build_scanned(born, scanned)
    print(f"wrote {born} ({born.stat().st_size} bytes)")
    print(f"wrote {scanned} ({scanned.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
